import { GoogleGenAI, Type } from "@google/genai";
import { AnalysisResult, ModelType } from "../types";
import { fileToBase64 } from "../utils";

export class GeminiService {
  private ai: GoogleGenAI | null = null;

  constructor(apiKey: string) {
    if (apiKey) {
      this.ai = new GoogleGenAI({ apiKey });
    }
  }

  updateKey(apiKey: string) {
    this.ai = new GoogleGenAI({ apiKey });
  }

  async analyzeVideoForClips(videoFile: File): Promise<AnalysisResult> {
    if (!this.ai) throw new Error("Gemini API Key not set");

    const base64Video = await fileToBase64(videoFile);

    // Prompt engineered to act as the "Cutter" from the user's notes
    const prompt = `
      Analyze this video for a social media automation workflow. 
      I need you to identify natural cut points to split this video into clips of 5-10 seconds max.
      
      For each segment:
      1. Provide start and end timestamps.
      2. Describe the action briefly.
      3. CRITICAL: Determine if a specific physical product (bottle, bag, supplement container) is clearly being held or shown to the camera.
      
      Return JSON only.
    `;

    try {
      const response = await this.ai.models.generateContent({
        model: ModelType.ANALYSIS,
        contents: {
          parts: [
            { inlineData: { mimeType: videoFile.type, data: base64Video } },
            { text: prompt }
          ]
        },
        config: {
          responseMimeType: "application/json",
          responseSchema: {
            type: Type.OBJECT,
            properties: {
              segments: {
                type: Type.ARRAY,
                items: {
                  type: Type.OBJECT,
                  properties: {
                    start_time_seconds: { type: Type.NUMBER },
                    end_time_seconds: { type: Type.NUMBER },
                    description: { type: Type.STRING },
                    product_visible: { type: Type.BOOLEAN },
                  },
                  required: ["start_time_seconds", "end_time_seconds", "description", "product_visible"]
                }
              }
            }
          }
        }
      });

      if (response.text) {
        return JSON.parse(response.text) as AnalysisResult;
      }
      throw new Error("No response from Gemini");
    } catch (error) {
      console.error("Analysis failed:", error);
      throw error;
    }
  }

  async compositeProductIntoFrame(
    frameBase64: string, 
    productBase64: string, 
    promptOverride?: string
  ): Promise<string> {
    if (!this.ai) throw new Error("Gemini API Key not set");

    // This implements the "Nano Banana Pro" step: adding product to last frame
    const prompt = promptOverride || `
      This is a frame from a video. 
      I need you to realistically composite the product image provided into this scene.
      The person in the video should appear to be holding the product naturally, or the product should be on a surface nearby.
      Match the lighting and grain of the original video frame.
      Return only the image.
    `;

    // Note: In a real scenario, we might use 'gemini-3-pro-image-preview' to generate a NEW image
    // based on these inputs.
    
    // Since the API for direct image editing/composition is specific, we use the generateContent
    // capability with the image preview model which handles multimodal inputs to generation.
    try {
      const response = await this.ai.models.generateContent({
        model: ModelType.EDITING,
        contents: {
          parts: [
            { text: prompt },
            { inlineData: { mimeType: "image/jpeg", data: frameBase64 } },
            { inlineData: { mimeType: "image/jpeg", data: productBase64 } }
          ]
        }
      });
        
      // Extracting image from response
      // We iterate to find the image part
      if (response.candidates?.[0]?.content?.parts) {
         for (const part of response.candidates[0].content.parts) {
             if (part.inlineData && part.inlineData.data) {
                 return part.inlineData.data;
             }
         }
      }
      throw new Error("No image generated by Nano Banana");
    } catch (error) {
        console.error("Composite failed", error);
        throw error;
    }
  }
}
